apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - name: http
      port: {{ .Values.networking.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.mcp.enabled }}
    - name: mcp
      port: {{ .Values.networking.mcp.port }}
      targetPort: mcp
      protocol: TCP
    {{- end }}
    {{- if .Values.portal.enabled }}
    - name: portal
      port: {{ .Values.networking.portal.port }}
      targetPort: portal
      protocol: TCP
    {{- end }}
  selector:
    {{- include "library-chart.selectorLabels" . | nindent 4 }}
